# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='time',
            field=models.DateField(auto_now=True),
        ),
    ]
