# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='passwd',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='note',
            name='ref',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
