# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('polls', '0002_question_hello'), ('polls', '0003_remove_question_hello')]

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
    ]
